---
title: "NLP testing"
output: github_document
---

```{r setup, include=FALSE}
library(lubridate)
library(tidyverse)
library(tidytext)
```

```{r load}
tweets = read.csv("../data/candidate_tweets.csv")
tweets$text <- as.character(tweets$text)
```


```{r tidy_words}

# Get one word per row.
tweet_words <- tweets %>%
        unnest_tokens(word, text)

# Clean out highly common and uninformative words.
cleaned_tweet_words <- tweet_words %>%
        
        # Remove stop words.
        anti_join(stop_words) %>%
        
        # Remove html and retweet tokens.
        filter(word != "https",
               word != "t.co",
               word != "rt")


breaking_tweets <- cleaned_tweet_words %>%
        
        # Count the number of unique tweets and unique authors using each word.
        group_by(word) %>%
        summarise(distinct_tweets = n_distinct(tweet_url),
                  distinct_authors = n_distinct(screen_name)) %>%
        arrange(desc(distinct_authors), desc(distinct_tweets)) %>% 
        
        # Join with the dataframe containing one row per word.
        right_join(cleaned_tweet_words) %>% 
        
        # Count the number of authors tweeting words that are present in each tweet.
        group_by(tweet_url) %>%
        summarise(num_authors_tweeting_present_word = sum(distinct_authors)) %>% 
        
        # Join with the original tweets.
        right_join(tweets) %>% 
        
        # Order by the tweets with the greatest number of words that are present
        # across the broadest range of authors.
        arrange(desc(num_authors_tweeting_present_word))

max_num_auth <- max(breaking_tweets$num_authors_tweeting_present_word)
max_fav <- max(breaking_tweets$favorite_count)
max_rt <- max(breaking_tweets$retweet_count)

breaking_tweets %>%
        mutate(time_diff = as.numeric(now("UTC") - parse_date_time(created_at_stamp, "Ymd HMS"))) %>% 
        mutate(notif_score = (num_authors_tweeting_present_word/max_num_auth) +
                       (favorite_count/max_fav) +
                       (retweet_count/max_rt) -
                       time_diff) %>% 
        arrange(desc(notif_score))

```








